
package com.bizvision.dpf.processor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IProcessor", targetNamespace = "http://server.dpf.bizvision.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IProcessor {


    /**
     * 
     * @param task
     * @return
     *     returns com.bizvision.dpf.processor.Result
     * @throws ProcessException
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.dpf.bizvision.com/IProcessor/executeRequest", output = "http://server.dpf.bizvision.com/IProcessor/executeResponse", fault = {
        @FaultAction(className = ProcessException.class, value = "http://server.dpf.bizvision.com/IProcessor/execute/Fault/Exception")
    })
    public Result execute(
        @WebParam(name = "task", partName = "task")
        Task task)
        throws ProcessException
    ;

    /**
     * 
     * @return
     *     returns com.bizvision.dpf.processor.ProcessorPerformence
     * @throws ProcessException
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.dpf.bizvision.com/IProcessor/getProcessorPerformenceRequest", output = "http://server.dpf.bizvision.com/IProcessor/getProcessorPerformenceResponse", fault = {
        @FaultAction(className = ProcessException.class, value = "http://server.dpf.bizvision.com/IProcessor/getProcessorPerformence/Fault/Exception")
    })
    public ProcessorPerformence getProcessorPerformence()
        throws ProcessException
    ;

}
