
package com.bizvision.dpf.processor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProcessorService", targetNamespace = "http://server.dpf.bizvision.com/", wsdlLocation = "http://127.0.0.1:10080/processor?wsdl")
public class ProcessorService
    extends Service
{

    private final static URL PROCESSORSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSORSERVICE_EXCEPTION;
    private final static QName PROCESSORSERVICE_QNAME = new QName("http://server.dpf.bizvision.com/", "ProcessorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:10080/processor?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSORSERVICE_WSDL_LOCATION = url;
        PROCESSORSERVICE_EXCEPTION = e;
    }

    public ProcessorService() {
        super(__getWsdlLocation(), PROCESSORSERVICE_QNAME);
    }

    public ProcessorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSORSERVICE_QNAME, features);
    }

    public ProcessorService(URL wsdlLocation) {
        super(wsdlLocation, PROCESSORSERVICE_QNAME);
    }

    public ProcessorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSORSERVICE_QNAME, features);
    }

    public ProcessorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IProcessor
     */
    @WebEndpoint(name = "ProcessorPort")
    public IProcessor getProcessorPort() {
        return super.getPort(new QName("http://server.dpf.bizvision.com/", "ProcessorPort"), IProcessor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IProcessor
     */
    @WebEndpoint(name = "ProcessorPort")
    public IProcessor getProcessorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.dpf.bizvision.com/", "ProcessorPort"), IProcessor.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSORSERVICE_EXCEPTION!= null) {
            throw PROCESSORSERVICE_EXCEPTION;
        }
        return PROCESSORSERVICE_WSDL_LOCATION;
    }

}
