
package com.bizvision.dpf.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

import com.bizvision.dpf.server.ProcessorPersistable;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IPersistence", targetNamespace = "http://persistence.dpf.bizvision.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IPersistence {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://persistence.dpf.bizvision.com/IPersistence/listTaskAllocatorsRequest", output = "http://persistence.dpf.bizvision.com/IPersistence/listTaskAllocatorsResponse")
    public String listTaskAllocators();

    /**
     * 
     * @param state
     * @param url
     */
    @WebMethod
    @Action(input = "http://persistence.dpf.bizvision.com/IPersistence/updateTaskAllocatorStateRequest", output = "http://persistence.dpf.bizvision.com/IPersistence/updateTaskAllocatorStateResponse")
    public void updateTaskAllocatorState(
        @WebParam(name = "url", partName = "url")
        String url,
        @WebParam(name = "state", partName = "state")
        int state);

    /**
     * 
     * @param persistable
     */
    @WebMethod
    @Action(input = "http://persistence.dpf.bizvision.com/IPersistence/updateProcessorRequest", output = "http://persistence.dpf.bizvision.com/IPersistence/updateProcessorResponse")
    public void updateProcessor(
        @WebParam(name = "persistable", partName = "persistable")
        ProcessorPersistable persistable);

}
