
package com.bizvision.dpf.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersistenceService", targetNamespace = "http://persistence.dpf.bizvision.com/", wsdlLocation = "http://127.0.0.1:8199/persistence?wsdl")
public class PersistenceService
    extends Service
{

    private final static URL PERSISTENCESERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSISTENCESERVICE_EXCEPTION;
    private final static QName PERSISTENCESERVICE_QNAME = new QName("http://persistence.dpf.bizvision.com/", "PersistenceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8199/persistence?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSISTENCESERVICE_WSDL_LOCATION = url;
        PERSISTENCESERVICE_EXCEPTION = e;
    }

    public PersistenceService() {
        super(__getWsdlLocation(), PERSISTENCESERVICE_QNAME);
    }

    public PersistenceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSISTENCESERVICE_QNAME, features);
    }

    public PersistenceService(URL wsdlLocation) {
        super(wsdlLocation, PERSISTENCESERVICE_QNAME);
    }

    public PersistenceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSISTENCESERVICE_QNAME, features);
    }

    public PersistenceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersistenceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IPersistence
     */
    @WebEndpoint(name = "PersistencePort")
    public IPersistence getPersistencePort() {
        return super.getPort(new QName("http://persistence.dpf.bizvision.com/", "PersistencePort"), IPersistence.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IPersistence
     */
    @WebEndpoint(name = "PersistencePort")
    public IPersistence getPersistencePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://persistence.dpf.bizvision.com/", "PersistencePort"), IPersistence.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSISTENCESERVICE_EXCEPTION!= null) {
            throw PERSISTENCESERVICE_EXCEPTION;
        }
        return PERSISTENCESERVICE_WSDL_LOCATION;
    }

}
