package com.sg.cdf.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-07-22T21:50:30.368+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebServiceClient(name = "DistributionService", 
                  wsdlLocation = "http://localhost:9000/distribution?wsdl",
                  targetNamespace = "http://service.ws.cdf.sg.com/") 
public class DistributionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.cdf.sg.com/", "DistributionService");
    public final static QName DistributionServicePort = new QName("http://service.ws.cdf.sg.com/", "DistributionServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:9000/distribution?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DistributionService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:9000/distribution?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DistributionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DistributionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DistributionService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DistributionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DistributionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public DistributionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns DistributionServicePortType
     */
    @WebEndpoint(name = "DistributionServicePort")
    public DistributionServicePortType getDistributionServicePort() {
        return super.getPort(DistributionServicePort, DistributionServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DistributionServicePortType
     */
    @WebEndpoint(name = "DistributionServicePort")
    public DistributionServicePortType getDistributionServicePort(WebServiceFeature... features) {
        return super.getPort(DistributionServicePort, DistributionServicePortType.class, features);
    }

}
