package com.sg.cdf.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-07-22T21:50:30.274+08:00
 * Generated source version: 3.0.0
 * 
 */
@WebService(targetNamespace = "http://service.ws.cdf.sg.com/", name = "DistributionServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface DistributionServicePortType {

    @RequestWrapper(localName = "distribute", targetNamespace = "http://service.ws.cdf.sg.com/", className = "com.sg.cdf.wsclient.Distribute")
    @WebMethod
    @ResponseWrapper(localName = "distributeResponse", targetNamespace = "http://service.ws.cdf.sg.com/", className = "com.sg.cdf.wsclient.DistributeResponse")
    public void distribute(
        @WebParam(name = "arg0", targetNamespace = "http://service.ws.cdf.sg.com/")
        com.sg.cdf.wsclient.RequestBuilder arg0
    );
}
